server:
  port: 8082

bridge:
  url: localhost:8080

jwt:
  expiration: 86400000
  secret: 3FC5D3C8D03FC2AC2AC3BB0BA2CEB2B33C258CED644FC5798AB6960CAFBAD0A6

management:
  endpoints:
    web:
      exposure:
        include: health, info