coverage:
  status:
    patch: off
    project:
      HomexGateway:
        paths:
          - "homex-gateway/"
        target: 85%
      HomexBridge:
        paths:
          - "homex-bridge/"
        target: 85%
      HomexDummyEdge:
        paths:
          - "homex-dummy-edge/"
        target: 85%