coverage:
  status:
    patch: off
    project:
      HomexGateway:
        paths:
          - "homex-gateway/"
        target: 85%
      HomexData:
        paths:
          - "homex-data/"
        target: 85%
      HomexDummyEdge:
        paths:
          - "homex-dummy-edge/"
        target: 85%