coverage:
  status:
    project:
      HomexBridge:
        paths:
          - "homex-bridge/"
        target: 85%
      HomexDummyEdge:
        paths:
          - "homex-dummy-edge/"
        target: 85%