coverage:
  status:
    project:
      HomexBridge:
        paths:
          - "homex-bridge/"
        target: 85%
# Coverage for Edge not yet available
#      HomexEdge:
#        paths:
#          - "homex-edge/"
#        target: 85%