coverage:
  status:
    project:
      HomexCore:
        paths:
          - "homex-core/"
        target: 85%
      HomexEdge:
        paths:
          - "homex-edge/"
        target: 85%
      HomexAuth:
        paths:
          - "homex-auth/"
        target: 85%