language: java
jdk:
  - oraclejdk8
sudo: false
script: mvn clean verify

after_success:
  - bash <(curl -s https://codecov.io/bash) -F unittests -f */target/site/jacoco/jacoco.xml -t a00c4d12-594b-4ddc-ad5a-1b9fc85f0a01
  - bash <(curl -s https://codecov.io/bash) -F integration -f */target/site/jacoco-it/jacoco.xml -t a00c4d12-594b-4ddc-ad5a-1b9fc85f0a01