server:
  port: 8082

spring:
  profiles:
    active: dev
  datasource:
    url: "jdbc:h2:mem:${DB_NAME:test}"
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin}
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: create
    show-sql: false
  jackson:
    serialization:
      indent_output: true
  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  expiration: 86400000
  secret: 3FC5D3C8D03FC2AC2AC3BB0BA2CEB2B33C258CED644FC5798AB6960CAFBAD0A6

influx:
  url: http://localhost:8086
  user: admin
  password: admin
  database: measurement

management:
  endpoints:
    web:
      exposure:
        include: health, info