app:
  receive:
    queue: "message-in"
    topic: "message-in-ex"


spring:
  datasource:
    url: "jdbc:postgresql://192.168.0.250:5432/shas-db"
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: create
    show-sql: false
  jackson:
    serialization:
      indent_output: true
  rabbitmq:
    host: 192.168.0.250
    port: 5672
    username: guest
    password: guest