server:
  port: 8081

spring:
  datasource:
    url: "jdbc:postgresql://192.168.1.250:5432/shas-db"
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: create
    show-sql: false
  jackson:
    serialization:
      indent_output: true