server:
  port: 8081

edge:
  publishDelay: 10000
  publishPeriod: 5000
  contract:
    device:
      name: dummy-edge
      deviceType: SOURCE
      host: localhost
      port: ${server.port}
    measurements:
      DOUBLE:
        - name: "temperature"
          min: 16
          max: 26
      INT:
        - name: "humidity"
          min: 0
          max: 100

gateway:
  url: localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: health, info